spring:
  kafka:
    bootstrap-servers: localhost:9092
    in-group-id: in_group
    out-group-id: out_group

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: ing_hub
    password: 123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa.hibernate:
    ddl-auto: none

  jpa:
    properties:
      hibernate:
        format_sql: true
        query:
          fail_on_pagination_over_collection_fetch: true

  flyway:
    baselineOnMigrate: true
    locations:
      - db/migration

logging:
  level.root: info
  level:
    org.apache.kafka: ERROR
    org.springframework.orm.jpa.JpaTransactionManager: trace
    org.springframework.kafka.transaction: trace
    #    org.springframework.kafka.core.DefaultKafkaProducerFactory: trace
    com.learn.spring: debug
    org.springframework.jdbc.core: TRACE
